/******************************************************************************
* File Name: secure_keys.h
*
* Description: This file contains configuration parameters for the secure HTTP
* server and the server security keys such as server certificate, private key,
* and the root CA (certificate authority) to trust the client.
*
* Related Document: See README.md
*******************************************************************************
* Copyright 2020-2021, Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
*
* This software, including source code, documentation and related
* materials ("Software") is owned by Cypress Semiconductor Corporation
* or one of its affiliates ("Cypress") and is protected by and subject to
* worldwide patent protection (United States and foreign),
* United States copyright laws and international treaty provisions.
* Therefore, you may use this Software only as provided in the license
* agreement accompanying the software package from which you
* obtained this Software ("EULA").
* If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
* non-transferable license to copy, modify, and compile the Software
* source code solely for use in connection with Cypress's
* integrated circuit products.  Any reproduction, modification, translation,
* compilation, or representation of this Software except as specified
* above is prohibited without the express written permission of Cypress.
*
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
* reserves the right to make changes to the Software without notice. Cypress
* does not assume any liability arising out of the application or use of the
* Software or any product or circuit described in the Software. Cypress does
* not authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death ("High Risk Product"). By
* including Cypress's product in a High Risk Product, the manufacturer
* of such system or application assumes all risk of such use and in doing
* so agrees to indemnify Cypress against all liability.
*******************************************************************************/

/*******************************************************************************
* Include guard
*******************************************************************************/
#ifndef SECURE_KEYS_H_
#define SECURE_KEYS_H_

/* HTTPS server certificate. Copy from the HTTPS server certificate
 * generated by OpenSSL (See Readme.md on how to generate a SSL certificate).
 */
#define keySERVER_CERTIFICATE_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIID5DCCAsygAwIBAgIUKX5XOQDInm7k6nj97YjxnMJVWsYwDQYJKoZIhvcNAQEL\n"\
"BQAwezELMAkGA1UEBhMCSU4xEjAQBgNVBAgMCUthcm5hdGFrYTESMBAGA1UEBwwJ\n"\
"QmVuZ2FsdXJ1MQswCQYDVQQKDAJDWTEUMBIGA1UECwwLRW5naW5lZXJpbmcxITAf\n"\
"BgNVBAMMGG15c2VjdXJlaHR0cHNlcnZlci5sb2NhbDAeFw0yMjA0MTcyMjMxMDla\n"\
"Fw0zMjA0MTQyMjMxMDlaMHsxCzAJBgNVBAYTAklOMRIwEAYDVQQIDAlLYXJuYXRh\n"\
"a2ExEjAQBgNVBAcMCUJlbmdhbHVydTELMAkGA1UECgwCQ1kxFDASBgNVBAsMC0Vu\n"\
"Z2luZWVyaW5nMSEwHwYDVQQDDBhteXNlY3VyZWh0dHBzZXJ2ZXIubG9jYWwwggEi\n"\
"MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDfb5kP2b7QjlT6Cq370zu+psOu\n"\
"7krUZSAArTfrthxwZdpL9I354xnxzZCEO5vouQiz686PhML8o6mMs4D+OmueVhNO\n"\
"55FzJaDgwLugK6n9/cFmM3J9RGOosgshUWZbHpFla9LdiYsQ7HQNjLA32VoLq5O/\n"\
"Z6yCp2FCg19LjJD3uLoCu5srlgtrGRPwgv3ISjcx7pKPLWPOv7GyzxAYH1I3FpzV\n"\
"FdTpV35SSAdENZa2eOgOEb0ZJc/RjHc31n2N8zqMIaWMdT2YKs3lLk2yhqF5GUzt\n"\
"xkURVyUcTquL1AzaUHCjLlvbWRjMFnHrWQ8ZWEAhEW1zomLCLQ5xYZ+vNRldAgMB\n"\
"AAGjYDBeMB8GA1UdIwQYMBaAFGUqGmf44MyOuQPdNrMP00WeveYEMAkGA1UdEwQC\n"\
"MAAwCwYDVR0PBAQDAgTwMCMGA1UdEQQcMBqCGG15c2VjdXJlaHR0cHNlcnZlci5s\n"\
"b2NhbDANBgkqhkiG9w0BAQsFAAOCAQEAWxdQ+TfuusPPCfDGheC2jCGGfYhzC9A9\n"\
"4ZkrJyj/H7DCkPntNxJzjNjcS0s1pVuO2W7re+NCKdf+VIEHRrUp7Kcf6l/cYhA3\n"\
"SuDVNoYIJJ47yzIYfksDgkd4qml+mIkAO8Lsb79+gWc58ZL2bs8dGDhiYY/a9h7X\n"\
"l4IDBxoTEur5f6G1tU1m+qxdsaXU//tOuLn0N7NabPuHLKKpqTANgAKp/e9seN5K\n"\
"ZwxQb1EjNqwirKQkyTY5AdzCJWwIaAjtJnM7Z4U1lAnDeMBmPfPhJT1WxOnLywU0\n"\
"HmX5kzZ8ee/UNyPQuR9UTfLRbQXIWERFhyl4oQQ2Y9/o+kRJAGCjAQ==\n"\
"-----END CERTIFICATE-----"

/* Private key of the HTTPS server. Copy from the HTTPS server key
 * generated by OpenSSL (See Readme.md on how to create a private key).
 */
#define keySERVER_PRIVATE_KEY_PEM \
"-----BEGIN RSA PRIVATE KEY-----\n"\
"MIIEpQIBAAKCAQEA32+ZD9m+0I5U+gqt+9M7vqbDru5K1GUgAK0367YccGXaS/SN\n"\
"+eMZ8c2QhDub6LkIs+vOj4TC/KOpjLOA/jprnlYTTueRcyWg4MC7oCup/f3BZjNy\n"\
"fURjqLILIVFmWx6RZWvS3YmLEOx0DYywN9laC6uTv2esgqdhQoNfS4yQ97i6Arub\n"\
"K5YLaxkT8IL9yEo3Me6Sjy1jzr+xss8QGB9SNxac1RXU6Vd+UkgHRDWWtnjoDhG9\n"\
"GSXP0Yx3N9Z9jfM6jCGljHU9mCrN5S5NsoaheRlM7cZFEVclHE6ri9QM2lBwoy5b\n"\
"21kYzBZx61kPGVhAIRFtc6Jiwi0OcWGfrzUZXQIDAQABAoIBAQCfIghNdbOlLfnv\n"\
"q7OGa0dd3b/40taQtwU39iahxi4zDxeOiTqlAs3znYiT5TCBa2d7XTLcnJ2S+a1D\n"\
"/ISejFUhjARsahj5fY87A4md5ftIXnZjp7ie5xpjh4rNy/+uXfMH3OdtyQw2nXF6\n"\
"RP0siazMKwMri1ceJr/qc05nrFGDW8S0Hy4gMqWKz6Aza9ufJtDcxFCTM5OpQdWq\n"\
"qq9O/b6XllHHjH2+Bxtxx9ZXvc8qG9QLjrZpvtAVHd2XGymuNePEJoexDmdBLP+M\n"\
"ugUbdYPJdT2jV3lZJ1XW431SqTZWA66vMyWEXWbsWLGR+iT2QcYEJPEYiSN0VyY0\n"\
"HJRjiX2xAoGBAPWNg1WwHuwhS+hms2yYwSkWQNkwlb53Y06hQwbRqKQP8zvhMbPy\n"\
"CTvjkPhxK++o2TOHXS+S7ozDuHTqEeue7JPVBKo8I1t206rEEdXguhyp7condmjo\n"\
"RFaSrbNQbPCLm8hdvdJXFjS05GePIyRsbVnomTTmcgS99Bc7WEWfnGD/AoGBAOjx\n"\
"Mdph0KTBAjkDhm31O0LfV2OMgj163v4a3nK/CBoJ+hre+Kf2KQWXnMDFBKgVs+YR\n"\
"DlutdQI56e7AU4+I7TxTD6p5BrLPrxtEEpBREk8nROuoxtQbB3K8H7UAMunaa7VD\n"\
"0/r2kQ/ITozKrCCCoIxfPZgx9N7D6BYl+/dyZamjAoGBAJJveRIhvN8eoDERBhFO\n"\
"K2tAPR4IzlROyGc83kbzwzlL1ccw7b4dKgqQFIVEoGoE7LrBD/5uBlrl4Vu/tz4n\n"\
"gXhLwcNvp7pE68fbs7MzmGm9oPQ8gm3fjdl/EZ1s6fqtlxJvbONCUhjOg6OKhe+T\n"\
"xcanYq5ce0R+r1Enb+XdYJmrAoGAIWof5ZysakXJhNYtnW5VHuWcyonoUNtkS30d\n"\
"NcaTafDOcLZVYvqbrdKuyLQ6U8YxNSpzLdF2/GfEV9w84FUa+tFLaP/NZy8FhlrA\n"\
"cvU+NB6E820VgG2UJvA3eCZcJ1GOq8TcDp759hKcufOEt3EliJ1M350i7CWcEDlI\n"\
"qJk/XhMCgYEAsN913yNhP6AzYuuY8kxytGpXa4qwDmQwBvBCrGU3N5vBH0UPCxT4\n"\
"FG7MIjuGExO40DdZfouMwrAcP/Uc79bkCHgF1IJfDhvc3cXBprPGycFrgTcFPOvC\n"\
"KZ1V0fS7JyjR1NafQMu+V65XsFTNRAzXd+Y7kWpjMLOfUSksbeDHk7Q=\n"\
"-----END RSA PRIVATE KEY-----"


/* HTTPS client certificate. In this example this is the RootCA
 * certificate so as to verify the HTTPS client's identity. */
#define keyCLIENT_ROOTCA_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIID1zCCAr+gAwIBAgIUD6QGmwPR+sLXCTpAr0ofr9SGGwUwDQYJKoZIhvcNAQEL\n"\
"BQAwezELMAkGA1UEBhMCSU4xEjAQBgNVBAgMCUthcm5hdGFrYTESMBAGA1UEBwwJ\n"\
"QmVuZ2FsdXJ1MQswCQYDVQQKDAJDWTEUMBIGA1UECwwLRW5naW5lZXJpbmcxITAf\n"\
"BgNVBAMMGG15c2VjdXJlaHR0cHNlcnZlci5sb2NhbDAeFw0yMjA0MTcyMjMxMDla\n"\
"Fw0zMjA0MTQyMjMxMDlaMHsxCzAJBgNVBAYTAklOMRIwEAYDVQQIDAlLYXJuYXRh\n"\
"a2ExEjAQBgNVBAcMCUJlbmdhbHVydTELMAkGA1UECgwCQ1kxFDASBgNVBAsMC0Vu\n"\
"Z2luZWVyaW5nMSEwHwYDVQQDDBhteXNlY3VyZWh0dHBzZXJ2ZXIubG9jYWwwggEi\n"\
"MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDooBWU6HpjNJQkaiN9RCx3Z9fY\n"\
"IjOVESWXYwIRYNWB6SSMbDPooNQ9Y1q9hWApkbi38yfX+y8f+3yTNoZAsl1oenEf\n"\
"1HKa8MVEwoFGQezXWlck/b34VwgRhunPrGugf4Ca1mRnHFd+hTwrOWjSX/fA1czD\n"\
"Egfq5YRdVr7aa0a3o1hP7SF7rgm2JNfzPyRv9aboYmY0UQIL+i7rnspGNRDc446d\n"\
"ACXArHRXTM/FPlzy2tWarPWYuC3d+VPc8XrWYDCy8HxMz97+lUNVj9kvQ66zfGPO\n"\
"8yebIiTha7M862DzkX6VRoXuCV/HRdvkemBaLBZsTjLgPEK0rdKZK2a/cYC7AgMB\n"\
"AAGjUzBRMB0GA1UdDgQWBBRlKhpn+ODMjrkD3TazD9NFnr3mBDAfBgNVHSMEGDAW\n"\
"gBRlKhpn+ODMjrkD3TazD9NFnr3mBDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3\n"\
"DQEBCwUAA4IBAQAfx9yJ0BiK6TkxZGYuQpsIdQ+E+J3yJCp7XTqjuhUMcztViPlM\n"\
"cKdrB6KmkhOTiIJRTQL7pgyDWRGQCMdVfV/Iv5gu00cwcUDsKSpa1kOAE41cAztg\n"\
"fh4XyF+DZIT5LTmANwz1z33JSXLQI2o6wE8qJ0uN+LPOg2nWIfDjMG6eeveKrp/L\n"\
"Qm+G+eVI5nNU0grySvcM8fkjKhU1EI28aatNdhhrwLtC3/xTkSr984O23wYoTqKY\n"\
"TtX3cpgimLnvLxm0nkI4Gm6ShNxfpkpU3UpF/951Wey19pSXtNtaTjjW9FIOtkkx\n"\
"yH2paCUXfgKxZUjqvWy0rTfTnQe4zev24jOj\n"\
"-----END CERTIFICATE-----"

#endif /* SECURE_KEYS_H_ */

/* [] END OF FILE */
